version: "3.8"

services:
  zookeeper-electronic:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-electronic:
    image: confluentinc/cp-kafka:7.4.3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-electronic:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-electronic:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-electronic

  elasticsearch-electronic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.7
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - electronic-elastic:/usr/share/elasticsearch/data

  kibana-electronic:
    image: docker.elastic.co/kibana/kibana:8.18.7
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-electronic:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-electronic

  frontend-user-electronic:
    image: tdat/frontenduser-electronic:dev
    restart: always
    deploy:
      replicas: 1

    env_file:
      - ./frontendUser/.env.development
    expose:
      - 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app/
  user-electronic:
    image: tdat/user-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-electronic:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./user/.env
    expose:
      - 9000
    volumes:
      - .:/app/

  catalog-electronic:
    image: tdat/catalog-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-electronic:9200
    depends_on:
      - kafka-electronic
      - elasticsearch-electronic
    env_file:
      - ./catalog/.env
    expose:
      - 9001
    volumes:
      - .:/app/

  order-electronic:
    image: tdat/order-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-electronic:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./order/.env
    expose:
      - 9002
    volumes:
      - .:/app/

  payment-electronic:
    image: tdat/payment-electronic:dev
    restart: always
    deploy:
      replicas: 1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-electronic:9200
    depends_on:
      - kafka-electronic
    env_file:
      - ./payment/.env
    expose:
      - 9003
    volumes:
      - .:/app/

  nginx-electronic:
    container_name: nginx-electronic
    image: tdat/nginx-electronic:latest # owasp/modsecurity-crs:nginx #reverse-proxy # owasp/modsecurity-crs:nginx
    depends_on:
      - user-electronic
      - catalog-electronic
      - order-electronic
      - payment-electronic
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx

volumes:
  electronic-elastic:
    driver: local
